### PR TITLE
Add approvers to facilitate project management

### PR DESCRIPTION
**Pull request by brahmaroutu**
We would like to pick up pace in merging initial code to move to alpha implementation ASAP. This requires us to have some approvers who are involved deeply in this project. Please approve this PR ASAP to get help us carry the work at a faster pace.

/assign @xing-yang @saad-ali

### CODE REVIEW

**Comment by brahmaroutu** [comment]
@xing-yang I have made changes to limit the approvers and add more reviewers to this repo. Please review.

**Comment by brahmaroutu** [comment]
@saad-ali Can you please review.

**Comment by saad-ali** [comment]
Per our discussion at the COSI meeting today, let's hold off on this.

/hold

**Pull request closed without merging**
