### PR TITLE
fake client: code gen added

### PR DESCRIPTION
**Pull request by krishchow**
This PR aims to add some basic code generation to create a fake client for testing purposes based on the protobuf spec. This will be part of the build process.

The PR includes a clone of [krishchow/protoc-gen-gofake](urlgithub.com/krishchow/protoc-gen-gofake)

### CODE REVIEW

**Comment by krishchow** [comment]
cc @wlan0

**Comment by wlan0** [comment]
@saad-ali could you please merge this. This adds a fake client that we need for grpc API testing in CI

**Review by saad-ali — APPROVED** [review]
/approve

**Pull request merged**
